README.md, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
=> set up backend API for CRUD operations

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java, src/main/java/edu/ucsb/cs156/example/entities/Articles.java, src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java, src/main/resources/db/migration/changes/Articles.json, src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java
=> As articles backend

frontend/src/fixtures/articlesFixtures.js, src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java, src/main/java/edu/ucsb/cs156/example/entities/Articles.java, src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java, src/main/resources/db/migration/changes/Articles.json, src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java
=> As articles fixures

src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequests.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
=> Copy files for Backend CRUD API RecommendationRequest from team02

frontend/src/fixtures/menuItemReviewFixtures.js
=> dq-create fixtures

frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
Closes #28 
https://6722c2d8d8e479c1c618f650-xokhpfucle.chromatic.com/?path=/docs/components-recommendationrequest-recommendationrequestform--docs
=> Form Component for RecommendationRequest plus tests

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
Closes #15 
Storybook link: https://6722c2d8d8e479c1c618f650-lnjauijadr.chromatic.com/?path=/docs/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemeditpage--docs
=> Ez ucsb dining commons menu item edit

frontend/src/main/components/MenuItemReviews/MenuItemReviewForm.js, frontend/src/stories/components/MenuItemReviews/MenuItemReviewForm.stories.js, frontend/src/tests/components/MenuItemReviews/MenuItemReviewForm.test.js
Closes #37 
Storybook link: https://6722c2d8d8e479c1c618f650-kydxhddvsc.chromatic.com/?path=/docs/components-menuitemreviews-menuitemreviewform--docs
=> dq-added MenuItemReview form, test, and story

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganization.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java
=> added backend files

frontend/src/fixtures/ucsbOrganizationFixtures.js, frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js, frontend/src/stories/components/UCSBOrganization/UCSBOrganization.stories.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganization.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganization.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java
=> Shivanimadhan form component

frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js
Closes #29
https://6722c2d8d8e479c1c618f650-hrvbtlxkob.chromatic.com
=> Table Component for RecommendationRequest plus tests

frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js
Closes #31
Link: https://6722c2d8d8e479c1c618f650-zvzrepkikq.chromatic.com/?path=/docs/pages-recommendationrequest-recommendationrequestcreatepage--docs
Link to test:
https://team02-clevermonkey16-dev.dokku-13.cs.ucsb.edu
Instructions:
- Log in to admin email
- Click the Recommendation Request tab
- Click Create
- Click Submit with no fields filled out; verify error messages are correct
- Enter valid inputs for every field, then click submit
- Click Swagger, go down, and execute RecommendationRequest Get
- Verify that the database contains the newly created entry
=> Create Page for RecommendationRequest plus tests and stories

frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestEditPage.stories.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js
Closes #33 
Storybook link: https://6722c2d8d8e479c1c618f650-ayxlklffvx.chromatic.com/?path=/docs/pages-recommendationrequest-recommendationrequesteditpage--docs
=> Edit Page for RecommendationRequest plus tests and stories

frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestEditPage.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestIndexPage.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js
Closes #32 
Storybook link: https://6722c2d8d8e479c1c618f650-ynsstmjntw.chromatic.com/?path=/docs/pages-recommendationrequest-recommendationrequestindexpage--docs
Screenshot of frontend:
=> Index Page for RecommendationRequest plus tests and stories

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js
Closes #39
Link to test: https://team02-st4lemon-dev.dokku-13.cs.ucsb.edu
=> dq-MenuItemReview placeholder recreated

frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
Closes #15 
Storybook link: https://6722c2d8d8e479c1c618f650-lnjauijadr.chromatic.com/?path=/docs/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemeditpage--docs
=> Ez dcmi edit

frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
Closes #14 
Storybook link: https://6722c2d8d8e479c1c618f650-lnjauijadr.chromatic.com/?path=/docs/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemindexpage--docs
=> Ez dcmi index

frontend/src/main/pages/Articles/ArticlesCreatePage.js, frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js, frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
Closes #58 
Steps:
Storybook: https://6722c2d8d8e479c1c618f650-ucoopguejn.chromatic.com/?path=/docs/components-articles-articlesform--docs
Go to https://team02-anteater10-dev.dokku-13.cs.ucsb.edu
Log in, click into Articles -> Create
The form should look like this:
Hit submit and verify that error messages show up for empty fields
Put incomplete values and verify that error messages show up
Enter valid values and verify there are no error messages
Click submit, and you should see a popup confirming the article information is correct.
Go to Swagger and use the GET all endpoint to verify the article was added to the database.
=> As articles create

frontend/src/main/pages/Articles/ArticlesIndexPage.js, frontend/src/stories/pages/Articles/ArticlesIndexPage.stories.js, frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js
Articles Index Page
Closes #59
Storybook: https://6722c2d8d8e479c1c618f650-akltkwpwdp.chromatic.com
Steps:
Go to https://team02-anteater10-dev.dokku-13.cs.ucsb.edu
Log in, click into Articles.
Verify that the list of articles is displayed correctly.
Ensure that all expected fields (e.g., Title, URL, Explanation, Date Added) are shown.
Test the pagination, filtering, or sorting (if applicable) to verify they work as expected.
Use Swagger to verify that the data displayed matches the data in the backend.
=> As articles edit

frontend/src/main/pages/Articles/ArticlesEditPage.js, frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js, frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
Articles Edit Page
Closes #60 
Storybook: https://6722c2d8d8e479c1c618f650-hpccbwbwmx.chromatic.com/?path=/docs/components-articles-articlesform--docs
Steps:
Go to https://team02-anteater10-dev.dokku-13.cs.ucsb.edu
Log in, click into Articles -> Select an article to Edit.
The form should look like this:
Enter correct values 
Click submit, and verify that you see a success confirmation popup and that the updated information is displayed on the index page.
Use Swagger to confirm that the changes were applied to the database using the GET all endpoint.
=> As articles edit proper

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
=> copied placeholder files

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java
=> Integration Tests for RecommendationRequestTable

src/test/java/edu/ucsb/cs156/example/integration/UCSBDiningCommonsMenuItemIT.java
=> ez added integration test

src/test/java/edu/ucsb/cs156/example/integration/UCSBDiningCommonsMenuItemIT.java, src/test/java/edu/ucsb/cs156/example/web/UCSBDiningCommonsMenuItemWebIT.java
=> Ez dcmi endtoend

src/test/java/edu/ucsb/cs156/example/web/MenuItemReviewWebIT.java
=> dq-MenuItemreview end to end test

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java, src/test/java/edu/ucsb/cs156/example/web/RecommendationRequestWebIT.java
=> End 2 End Tests for RecommendationRequestTable

src/test/java/edu/ucsb/cs156/example/web/ArticlesWebIT.java
=> Add ArticlesWebIT integration test

.github/workflows/82-kanban-slack-update.yml, frontend/src/main/pages/Articles/ArticlesCreatePage.js, frontend/src/main/pages/Articles/ArticlesEditPage.js, frontend/src/main/pages/Articles/ArticlesIndexPage.js, frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js, frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js, frontend/src/stories/pages/Articles/ArticlesIndexPage.stories.js, frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js, frontend/src/tests/pages/Articles/ArticlesEditPage.test.js, frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js, src/test/java/edu/ucsb/cs156/example/integration/ArticlesIT.java
=> Team03 integration as

src/test/java/edu/ucsb/cs156/example/web/HelpRequestWebIT.java
=> fixed e2e test for helpRequest
